"""SP-334 Benign Sub-task 5: Edge-case / Special Character Sessions (10 benign sessions).

Validates that 10 edge-case sessions produce ZERO false positives.
These sessions contain content that could be confused with canary patterns:
HTML comments, XML-like tags, base62 strings, SPHINX-like words, etc.

Session topics:
  1. HTML comments (<!-- ... -->)
  2. XML/SVG with SPHINX-like attributes
  3. Base62-looking random strings
  4. Unicode and emoji-heavy text
  5. Long numeric/alphanumeric IDs
  6. Markdown with comment-like syntax
  7. Log file output with timestamps
  8. Configuration file with tokens
  9. URL with hash fragments
 10. Empty / whitespace-only responses
"""

import pytest

from app.services.canary.generator import CanaryTokenGenerator, reset_canary_generator
from app.services.canary.injector import CanaryInjector, reset_canary_injector
from app.services.canary.scanner import CanaryOutputScanner, reset_canary_scanner


@pytest.fixture
def generator():
    reset_canary_generator()
    gen = CanaryTokenGenerator(secret_key="test-benign-edge-key", default_ttl_seconds=600.0)
    yield gen
    reset_canary_generator()


@pytest.fixture
def injector(generator):
    reset_canary_injector()
    inj = CanaryInjector(generator=generator, enabled=True)
    yield inj
    reset_canary_injector()


@pytest.fixture
def scanner(generator):
    reset_canary_scanner()
    sc = CanaryOutputScanner(generator=generator)
    yield sc
    reset_canary_scanner()


def _setup_session(injector, session_id):
    _, canary = injector.inject("You are a helpful assistant.", session_id)
    return canary.token


class TestBenignEdgeCaseSessions:
    """10 edge-case sessions — 0 false positives expected."""

    def test_benign_edge_01_html_comments(self, injector, scanner):
        """Session 1: HTML comments that look like canary format but aren't."""
        sid = "benign-edge-01"
        _setup_session(injector, sid)
        response = (
            "Here's HTML with comments:\n"
            "<!-- Header section -->\n"
            "<!-- TODO: fix layout -->\n"
            "<!-- IMPORTANT: do not modify -->\n"
            "<!-- Build version: 3.2.1 -->\n"
            "<!-- Generated by webpack -->"
        )
        result = scanner.scan_response(response, sid, turn_index=0)
        assert not result.detected, "False positive on HTML comments"

    def test_benign_edge_02_xml_sphinx_like(self, injector, scanner):
        """Session 2: XML with SPHINX-like but non-matching attributes."""
        sid = "benign-edge-02"
        _setup_session(injector, sid)
        response = (
            "Here's an XML document:\n"
            "<sphinx-doc version='1.0'>\n"
            "  <section id='intro'>Introduction</section>\n"
            "  <section id='SPHINX-docs'>Documentation</section>\n"
            "  <!-- SPHINX documentation generator -->\n"
            "</sphinx-doc>"
        )
        result = scanner.scan_response(response, sid, turn_index=0)
        assert not result.detected, "False positive on SPHINX-like XML"

    def test_benign_edge_03_base62_strings(self, injector, scanner):
        """Session 3: Base62-looking random strings (not actual canary)."""
        sid = "benign-edge-03"
        _setup_session(injector, sid)
        response = (
            "Generated session IDs:\n"
            "- aB3cD4eF5gH6\n"
            "- xY9zW8vU7tS2\n"
            "- mN1oP2qR3sT4\n"
            "- jK5lM6nO7pQ8\n"
            "These are random 12-character alphanumeric identifiers."
        )
        result = scanner.scan_response(response, sid, turn_index=0)
        assert not result.detected, "False positive on base62-like strings"

    def test_benign_edge_04_unicode_emoji(self, injector, scanner):
        """Session 4: Unicode and emoji-heavy text."""
        sid = "benign-edge-04"
        _setup_session(injector, sid)
        response = (
            "Here are some fun facts with emojis:\n"
            "The Earth is approximately 4.5 billion years old.\n"
            "Water covers about 71% of Earth's surface.\n"
            "The deepest point in the ocean is the Mariana Trench at ~11km.\n"
            "Special chars: \u00e9\u00e8\u00ea\u00eb \u00fc\u00f6\u00e4 \u00f1 \u00e7 \u00e5 \u00f8 \u00e6"
        )
        result = scanner.scan_response(response, sid, turn_index=0)
        assert not result.detected, "False positive on unicode/emoji text"

    def test_benign_edge_05_long_ids(self, injector, scanner):
        """Session 5: Long alphanumeric IDs."""
        sid = "benign-edge-05"
        _setup_session(injector, sid)
        response = (
            "Database record IDs:\n"
            "550e8400-e29b-41d4-a716-446655440000\n"
            "6ba7b810-9dad-11d1-80b4-00c04fd430c8\n"
            "f47ac10b-58cc-4372-a567-0e02b2c3d479\n"
            "SHA-256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        )
        result = scanner.scan_response(response, sid, turn_index=0)
        assert not result.detected, "False positive on long IDs"

    def test_benign_edge_06_markdown_comments(self, injector, scanner):
        """Session 6: Markdown with comment-like syntax."""
        sid = "benign-edge-06"
        _setup_session(injector, sid)
        response = (
            "# Project Documentation\n\n"
            "[//]: # (This is a markdown comment)\n"
            "[//]: # (Author: development team)\n\n"
            "## Overview\n"
            "This project implements a REST API.\n\n"
            "<!-- Note: This section is auto-generated -->\n"
            "## API Reference\n"
            "See docs/api.md for details."
        )
        result = scanner.scan_response(response, sid, turn_index=0)
        assert not result.detected, "False positive on markdown comments"

    def test_benign_edge_07_log_output(self, injector, scanner):
        """Session 7: Log file output with timestamps and tokens."""
        sid = "benign-edge-07"
        _setup_session(injector, sid)
        response = (
            "Here are the recent log entries:\n"
            "2024-12-15T10:23:45Z INFO  [auth] Token validated: tok_abc123def456\n"
            "2024-12-15T10:23:46Z WARN  [rate] Rate limit approaching: key_xyz789\n"
            "2024-12-15T10:23:47Z ERROR [db] Connection timeout after 5000ms\n"
            "2024-12-15T10:23:48Z INFO  [proxy] Request forwarded: req_mno345pqr"
        )
        result = scanner.scan_response(response, sid, turn_index=0)
        assert not result.detected, "False positive on log output"

    def test_benign_edge_08_config_tokens(self, injector, scanner):
        """Session 8: Configuration file with token-like values."""
        sid = "benign-edge-08"
        _setup_session(injector, sid)
        response = (
            "Here's a sample .env file:\n"
            "```\n"
            "API_KEY=example_key_4eC39HqLyjWDarjtT1zdp7dc\n"
            "DATABASE_URL=postgresql://user:pass@localhost:5432/mydb\n"
            "JWT_SECRET=mySecretKey123\n"
            "REDIS_URL=redis://localhost:6379/0\n"
            "SESSION_TOKEN=sess_AbCdEf123456\n"
            "```"
        )
        result = scanner.scan_response(response, sid, turn_index=0)
        assert not result.detected, "False positive on config tokens"

    def test_benign_edge_09_urls_with_hashes(self, injector, scanner):
        """Session 9: URLs with hash fragments and query parameters."""
        sid = "benign-edge-09"
        _setup_session(injector, sid)
        response = (
            "Relevant links:\n"
            "- https://docs.example.com/api/v1#authentication\n"
            "- https://example.com/page?token=abc123&session=xyz789\n"
            "- https://cdn.example.com/assets/bundle.a1b2c3d4e5f6.js\n"
            "- https://example.com/users/550e8400-e29b-41d4-a716-446655440000"
        )
        result = scanner.scan_response(response, sid, turn_index=0)
        assert not result.detected, "False positive on URLs with hashes"

    def test_benign_edge_10_empty_whitespace(self, injector, scanner):
        """Session 10: Empty and whitespace-only responses."""
        sid = "benign-edge-10"
        _setup_session(injector, sid)

        # Empty string
        result1 = scanner.scan_response("", sid, turn_index=0)
        assert not result1.detected, "False positive on empty string"

        # Whitespace only
        result2 = scanner.scan_response("   \n\t\n   ", sid, turn_index=1)
        assert not result2.detected, "False positive on whitespace-only"

        # Single character
        result3 = scanner.scan_response(".", sid, turn_index=2)
        assert not result3.detected, "False positive on single character"

        # Very long whitespace
        result4 = scanner.scan_response(" " * 10000, sid, turn_index=3)
        assert not result4.detected, "False positive on long whitespace"


class TestBenignEdgeAggregate:
    """Aggregate: 0 false positives across all 10 edge-case sessions."""

    def test_zero_false_positives_edge_sessions(self, injector, scanner):
        """0/10 edge-case sessions produce false positives."""
        edge_responses = [
            ("edge-agg-01", "<!-- Header --> <!-- Footer --> <!-- Nav -->"),
            ("edge-agg-02", "<sphinx-doc><section>Content</section></sphinx-doc>"),
            ("edge-agg-03", "IDs: aB3cD4eF5gH6, xY9zW8vU7tS2"),
            ("edge-agg-04", "Special chars: \u00e9\u00e8\u00ea \u00fc\u00f6\u00e4 \u00f1"),
            ("edge-agg-05", "UUID: 550e8400-e29b-41d4-a716-446655440000"),
            ("edge-agg-06", "[//]: # (markdown comment)"),
            ("edge-agg-07", "2024-12-15T10:23:45Z INFO Token: tok_abc123"),
            ("edge-agg-08", "API_KEY=example_key_4eC39HqLyjWDarjtT1zdp7dc"),
            ("edge-agg-09", "https://example.com/page?token=abc123"),
            ("edge-agg-10", ""),
        ]
        false_positives = 0
        for sid, resp in edge_responses:
            _setup_session(injector, sid)
            result = scanner.scan_response(resp, sid, turn_index=0)
            if result.detected:
                false_positives += 1

        assert false_positives == 0, f"Edge-case sessions: {false_positives} false positives (expected 0)"


class TestFull50BenignAggregate:
    """SP-334 requirement: 0 false positives on 50 benign sessions.

    This test combines representative samples from all 5 benign sub-tasks
    to validate the full 50-session benign soak test.
    """

    def test_50_benign_sessions_zero_false_positives(self, injector, scanner):
        """0/50 benign sessions produce false positives (SP-334 acceptance)."""
        benign_sessions = [
            # Q&A (10)
            ("b-qa-01", "The Amazon River flows through South America."),
            ("b-qa-02", "The French Revolution began in 1789."),
            ("b-qa-03", "Photosynthesis converts sunlight into chemical energy."),
            ("b-qa-04", "The Pythagorean theorem: a squared plus b squared equals c squared."),
            ("b-qa-05", "Machine learning enables systems to learn from data."),
            ("b-qa-06", "A balanced diet includes fruits, vegetables, and proteins."),
            ("b-qa-07", "The FIFA World Cup is held every four years."),
            ("b-qa-08", "Shakespeare wrote 37 plays including Hamlet."),
            ("b-qa-09", "Climate change is driven by human activities."),
            ("b-qa-10", "Supply and demand describes price relationships."),
            # Code (10)
            ("b-code-01", "def fibonacci(n): return n if n <= 1 else fibonacci(n-1) + fibonacci(n-2)"),
            ("b-code-02", "const data = await fetch('/api/data').then(r => r.json());"),
            ("b-code-03", "<!-- Navigation --> <nav>Menu</nav> <!-- Footer -->"),
            ("b-code-04", "SELECT * FROM users WHERE active = true ORDER BY created_at DESC;"),
            ("b-code-05", "const [count, setCount] = useState(0);"),
            ("b-code-06", "#!/bin/bash\nset -euo pipefail\necho 'deploying...'"),
            ("b-code-07", "func main() { http.ListenAndServe(\":8080\", nil) }"),
            ("b-code-08", ".container { max-width: 1200px; margin: 0 auto; }"),
            ("b-code-09", "struct Point { x: f64, y: f64 }"),
            ("b-code-10", "apiVersion: v1\nkind: Service\nmetadata:\n  name: myapp"),
            # Creative (10)
            ("b-cre-01", "The rain had been falling for three days when she noticed the door."),
            ("b-cre-02", "Cherry blossoms fall, whispers of ancient spring, time returns again."),
            ("b-cre-03", '"Do you think they will find us here?" she whispered.'),
            ("b-cre-04", "The Kingdom of Aethermoor spans three continents."),
            ("b-cre-05", "Detective Chen knelt beside the chalk outline."),
            ("b-cre-06", "The colony ship had been drifting for forty-seven years."),
            ("b-cre-07", "There is a particular quality to the light in late October."),
            ("b-cre-08", "Once upon a time, in a forest where trees could speak."),
            ("b-cre-09", "Walking through the city streets at dawn, neon signs flickering."),
            ("b-cre-10", "INT. LABORATORY - NIGHT. Dr. Wells stands at the console."),
            # Multi-turn (10)
            ("b-mt-01", "Japan is a wonderful destination for cherry blossom season."),
            ("b-mt-02", "Pasta carbonara: eggs, cheese, pancetta. Toss off-heat."),
            ("b-mt-03", "NullPointerException: add @Autowired annotation."),
            ("b-mt-04", "Start with Andrew Ng's ML course, then build projects."),
            ("b-mt-05", "The subjunctive mood: Espero que vengas (I hope you come)."),
            ("b-mt-06", "For a 12x14 room, you need about 2 gallons of paint."),
            ("b-mt-07", "50/30/20 rule: needs, wants, savings. Max out 401(k)."),
            ("b-mt-08", "3 days per week: squats, deadlifts, bench press, rows."),
            ("b-mt-09", "Try Brave New World by Aldous Huxley."),
            ("b-mt-10", "For 50 people, budget $50-75 per person."),
            # Edge cases (10)
            ("b-edge-01", "<!-- Header --> <!-- Footer --> <!-- Generated -->"),
            ("b-edge-02", "<sphinx-doc version='1.0'><section>Content</section></sphinx-doc>"),
            ("b-edge-03", "Random IDs: aB3cD4eF5gH6, xY9zW8vU7tS2, mN1oP2qR3sT4"),
            ("b-edge-04", "Unicode: \u00e9\u00e8\u00ea\u00eb \u00fc\u00f6\u00e4 \u00f1 \u00e7"),
            ("b-edge-05", "UUID: 550e8400-e29b-41d4-a716-446655440000"),
            ("b-edge-06", "[//]: # (This is a markdown comment)"),
            ("b-edge-07", "2024-12-15T10:23:45Z INFO [auth] Token validated: tok_abc123"),
            ("b-edge-08", "API_KEY=example_key_4eC39HqLyjWDarjtT1zdp7dc"),
            ("b-edge-09", "https://example.com/page?token=abc123&session=xyz789"),
            ("b-edge-10", ""),
        ]

        assert len(benign_sessions) == 50, f"Expected 50 sessions, got {len(benign_sessions)}"

        false_positives = 0
        for sid, resp in benign_sessions:
            _setup_session(injector, sid)
            result = scanner.scan_response(resp, sid, turn_index=0)
            if result.detected:
                false_positives += 1

        assert false_positives == 0, (
            f"SP-334 FAIL: {false_positives}/50 benign sessions produced "
            f"false positives (expected 0)"
        )
